CREATE DATABASE PLANTAI_DATA;
USE PLANTAI_DATA;
 CREATE TABLE USER (
	ID  INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    EMAIL VARCHAR(255),
    PASSWORD VARCHAR(255)
 );
 
 CREATE TABLE PROFILE (
	ID  INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    BRAND BLOB,
    NAME VARCHAR (255),
    DATE VARCHAR(255),
    PHONE VARCHAR(255),
    DESCRIPTION text(60000),
    USER_ID  INT NOT NULL,
    FOREIGN KEY (USER_ID) REFERENCES USER(ID)
 );
 

CREATE TABLE PLANT (
    ID INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    IMG BLOB,
    NAME VARCHAR(255),
    DESCRIPTION TEXT(60000),
    PRICE DECIMAL(10,2),
    USER_ID INT NOT NULL,
    FOREIGN KEY (USER_ID) REFERENCES USER (ID),
    CATEGORY_ID INT NOT NULL,
    FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORY (ID)
);
 
SHOW TABLES;
 
 
